### ISSUE TITLE
What is the purpose of the Prompt class?

### ISSUE THREAD

**Issue by alexmojaki** [HazyResearch/manifest#30]
Why not just allow `manifest.run` to accept a callable directly?

**Comment by lorr1** [comment]
Two reasons mainly
(a) it's a bit nice semantically and for readability to see Prompt() rather than an arbitrary callable. We may also extend a Prompt class to be more structured. I.e. take in a prefix, suffix, and instruction and construct a prompt each time.
(b) We support saving and loading prompts so even if you're in an interactive session and lose the string, you can still load the prompt next time.
